config/routes.rb
Blog::Engine.routes.draw do
  resources :comments

  resources :articles

end

app/models/blog/article.rb
module Blog
  class Article < ActiveRecord::Base
    belongs_to :author, class_name: User
    has_many :comments


    scope :order_by_recent, -> { order("created_at DESC") }

    def author_name
      self.author.try(:name) || "Anonymous"
    end
  end
end

app/models/blog/comment.rb
module Blog
  class Comment < ActiveRecord::Base
    belongs_to :author, class_name: User
    belongs_to :article

    scope :order_by_recent, -> { order("created_at DESC") }
    
    def author_name
      self.author.try(:name) || "Anonymous"
    end

    def author_avatar
      image_url = self.author.image.photo.url(:small) rescue "/assets/small/missing.png"
      "<img class='img-circle' src='#{image_url}'>".html_safe
    end
  end
end

app/controllers/blog/application_controller.rb
module Blog
  class ApplicationController < ActionController::Base
    layout 'layouts/blog_layout'
  end
end

app/controllers/blog/articles_controller.rb
require_dependency "blog/application_controller"

module Blog
  class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    # GET /articles
    def index
      @articles = Article.all.order_by_recent
    end

    # GET /articles/1
    def show
      @comment = Comment.new
      @comments = @article.comments.order_by_recent
    end

    # GET /articles/new
    def new
      @article = Article.new
    end

    # GET /articles/1/edit
    def edit
    end

    # POST /articles
    def create
      @article = Article.new(article_params)

      if @article.save
        redirect_to @article, notice: 'Article was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /articles/1
    def update
      if @article.update(article_params)
        redirect_to @article, notice: 'Article was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /articles/1
    def destroy
      @article.destroy
      redirect_to articles_url, notice: 'Article was successfully destroyed.'
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def article_params
      params.require(:article).permit(:title, :content, :author_id, :enable)
    end
  end
end

app/controllers/blog/comments_controller.rb
require_dependency "blog/application_controller"

module Blog
  class CommentsController < ApplicationController
    before_action :set_comment, only: [:show, :edit, :update, :destroy]

    # GET /comments
    def index
      @comments = Comment.all
    end

    # GET /comments/1
    def show
    end

    # GET /comments/new
    def new
      @comment = Comment.new
    end

    # GET /comments/1/edit
    def edit
    end

    # POST /comments
    def create
      @comment = Comment.new(comment_params)

      if @comment.save
        redirect_to @comment.article, notice: 'Comment was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /comments/1
    def update
      if @comment.update(comment_params)
        redirect_to @comment, notice: 'Comment was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /comments/1
    def destroy
      @comment.destroy
      redirect_to comments_url, notice: 'Comment was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_comment
        @comment = Comment.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def comment_params
        params.require(:comment).permit(:article_id, :content, :author_id)
      end
  end
end

app/helpers/blog/application_helper.rb
module Blog
  module ApplicationHelper
    ALERT_TYPES = [:success, :info, :warning, :danger]

    def bootstrap_flash
      flash_messages = []
      flash.each do |type, message|
        # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
        next if message.blank?

        type = type.to_sym
        type = :success if type == :notice
        type = :danger  if type == :alert
        type = :danger  if type == :error
        next unless ALERT_TYPES.include?(type)

        Array(message).each do |msg|
          text = content_tag(:div,
                             content_tag(:button, raw("&times;"),
                                         :class => "close",
                                         "data-dismiss" => "alert",
                                         "aria-hidden" => "true",
                                         "type" => "button") +
                                 msg,
                             :class => "alert fade in alert-#{type} alert-dismissable")
          flash_messages << text if msg
        end
      end
      flash_messages.join("\n").html_safe
    end
  end
end

app/helpers/blog/articles_helper.rb
module Blog
  module ArticlesHelper
  end
end

app/helpers/blog/comments_helper.rb
module Blog
  module CommentsHelper
  end
end

app/views/blog/articles/_form.html.erb
<%= simple_form_for(@article, wrapper: :horizontal_form) do |f| %>
    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :content %>
      <%= f.hidden_field :author_id, value: current_user.try(:id) %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, "Save" %>
    </div>
<% end %>

app/views/blog/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/blog/articles/index.html.erb
<div class="row">
  <div class="col-lg-8">
    <% @articles.each do |article| %>
        <div class="panel panel-default">
          <div class="panel-heading background-white">
            <h2><%= link_to article.title.truncate(80), article %></h2>

            <div class="post-info">
              <%= article.created_at.to_date %> By
              <%= article.author_name %>
            </div>

          </div>
          <div class="panel-body post-content">
            <p><%= article.content.truncate(400) %></p>
          </div>
          <div class="footer-social">
            <div class="post-share">
              <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
              <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
              <a href="#" target="_blank"><i class="fa fa-google-plus"></i></a>
              <a href="#" target="_blank"><i class="fa fa-pinterest"></i></a>
            </div>
            <div class="post-comment">
              <i class="fa fa-comments-o"></i> <%= article.comments.count %> Comments
            </div>
            <div class="post-read-more pull-right">
              <%= link_to article do %>
                  <i class="fa fa-angle-double-right"></i>
              <% end %>
            </div>
          </div>
        </div>
    <% end %>
  </div>

  <div class="col-lg-4">
    <%= link_to 'Post an Article', new_article_path, class: 'btn btn-info btn-lg btn-block' %>
    <br>

    <div class="panel panel-default">
      <div class="panel-heading background-white">
        <h2>Popular Post</h2>
      </div>
      <div class="panel-body popular-post">
        <ul class="list-unstyled">
          <% @articles.each do |article| %>
              <li>
                <%= link_to article.title.truncate(50), article, class: 'title' %>
                <p class="short-desc"><%= article.content.truncate(200) %></p>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/blog/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

app/views/blog/articles/show.html.erb
<div class="row">

  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading background-white">
        <h2><%= link_to @article.title, @article %></h2>

        <div class="post-info">
          <%= @article.created_at.to_date %> By
          <%= @article.author_name %>
        </div>

      </div>
      <div class="panel-body post-content">
        <p><%= @article.content %></p>
      </div>
      <div class="footer-social">
        <div class="post-share">
          <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
          <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
          <a href="#" target="_blank"><i class="fa fa-google-plus"></i></a>
          <a href="#" target="_blank"><i class="fa fa-pinterest"></i></a>
        </div>
        <div class="post-comment">
          <i class="fa fa-comments-o"></i> <%= @comments.count %> Comments
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'blog/comments/form' %>
      </div>
    </div>
  </div>

  <div class="col-lg-12">
    <% @comments.each do |comment| %>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="col-lg-3">
              <div><%= image_tag "/small/missing.png", class: "img-circle" %></div>
              <div><%= comment.author_name %></div>
            </div>
            <div class="col-lg-9">
              <%= comment.content %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/blog/comments/_form.html.erb
<%= simple_form_for(@comment) do |f| %>
    <div class="form-inputs">
      <%= f.input :content, label: false %>
      <%= f.hidden_field :article_id, value: @article.id %>
      <%= f.hidden_field :author_id, value: current_user.try(:id) %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, "Post Comments" %>
    </div>
<% end %>

app/views/blog/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/blog/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Article</th>
      <th>Content</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.article_id %></td>
        <td><%= comment.content %></td>
        <td><%= comment.author_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/blog/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

app/views/blog/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @comment.article_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Author:</strong>
  <%= @comment.author_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>